### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@yegor256 the PR is rather short, please review it

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 done, I added **16 mins** in payment `000-4c5b2735`, 21 hours and 31 mins spent to complete this. you're getting extra minutes here (c=1). +16 to your rating, your total score is [+4303](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
