### PR TITLE
#58

### PR DESCRIPTION
**Pull request by apocarteres**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@krzyk please review, thanks

**Comment by krzyk** [comment]
@apocarteres same problem here with travis

**Comment by dmarkov** [comment]
@krzyk Many thanks! **16 mins** were added to your account in Transaction ID `52104185`

extra minutes for review comments (c=1)

+16 added to your rating, current score is: [+4508](http://www.netbout.com/b/35035?open=rating)

**Pull request closed without merging**
